#!/usr/bin/env python3
"""Writes web/src/image/colorTableData.ts: the pseudo-colour tables of the display, from matplotlib.

Viridis and Magma (perceptually uniform, readable with colour-vision deficiencies; CC0) and Hot, each as 256 RGB bytes
for the display values 0-255 (matplotlib's colormap at i / 255, rounded to bytes). Gray and Inverted are computed in
web/src/image/colorTables.ts. Run with a Python that has matplotlib 3.11.2, e.g. the .venv-radiomics environment after
`uv pip install --python .venv-radiomics/bin/python matplotlib==3.11.2`:

    .venv-radiomics/bin/python scripts/colour-tables.py
"""

import base64
from pathlib import Path

import matplotlib
import numpy as np
from matplotlib import colormaps

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'web' / 'src' / 'image' / 'colorTableData.ts'
TABLES = ['viridis', 'magma', 'hot']


def table_bytes(name: str) -> bytes:
    colours = colormaps[name].resampled(256)(np.arange(256))[:, :3]
    return np.rint(colours * 255).astype(np.uint8).tobytes()


def main() -> None:
    lines = [
        f'// Generated by scripts/colour-tables.py from matplotlib {matplotlib.__version__}; do not edit.',
        '// Each table is 256 RGB bytes (768 bytes, base64) for the display values 0-255.',
        '',
        'export const COLOR_TABLE_DATA = {',
    ]
    for name in TABLES:
        lines.append(f"  {name}: '{base64.b64encode(table_bytes(name)).decode()}',")
    lines += ['} as const;', '']
    OUTPUT.write_text('\n'.join(lines))
    print(f'{OUTPUT.relative_to(ROOT)}: {", ".join(TABLES)} from matplotlib {matplotlib.__version__}')


if __name__ == '__main__':
    main()
